unsupported preprocessor versions clash with also built code versions of irq virtualized functions
This causes the really headscratching errors

In file included from /home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/uvisor-lib/uvisor-lib.h:45:0,
                 from /home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/source/interrupts.cpp:17:
/home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/uvisor-lib/unsupported.h:62:59: error: variable or field 'NVIC_SetVector' declared void
 #define vIRQ_SetVectorX(irqn, vector, flag) NVIC_SetVector((IRQn_Type) (irqn), (uint32_t) (vector))
                                                           ^
/home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/source/interrupts.cpp:20:6: note: in expansion of macro 'vIRQ_SetVectorX'
 void vIRQ_SetVectorX(uint32_t irqn, uint32_t vector, uint32_t flag)
      ^
/home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/source/interrupts.cpp:20:31: error: expected primary-expression before 'irqn'
 void vIRQ_SetVectorX(uint32_t irqn, uint32_t vector, uint32_t flag)
                               ^
/home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/uvisor-lib/unsupported.h:62:73: note: in definition of macro 'vIRQ_SetVectorX'
 #define vIRQ_SetVectorX(irqn, vector, flag) NVIC_SetVector((IRQn_Type) (irqn), (uint32_t) (vector))
                                                                         ^
/home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/source/interrupts.cpp:20:31: error: expected ')' before 'irqn'
 void vIRQ_SetVectorX(uint32_t irqn, uint32_t vector, uint32_t flag)
                               ^
/home/agreen/projects/mbed/mbed-client-examples/yotta_modules/uvisor-lib/uvisor-lib/unsupported.h:62:73: note: in definition of macro 'vIRQ_SetVectorX'
 #define vIRQ_SetVectorX(irqn, vector, flag) NVIC_SetVector((IRQn_Type) (irqn), (uint32_t) (vector))

This patch solves it by defeating build of the clashing code versions if YOTTA_CFG_UVISOR_PRESENT isn't around

Signed-off-by: Andy Green <andy.green@linaro.org>